# Use postgres/postgres user/password credentials
version: '3.9'

networks:
  fullstack:
    external: true

services:
  app:
    container_name: go-simple-chat
    build: .
    ports:
      - 8090:8090
    restart: on-failure
    depends_on:
      - db
    networks:
      - fullstack

  db:
    image: postgres
    restart: unless-stopped
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: chat
    ports:
      - 5432:5432
    networks:
      - fullstack

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - fullstack